sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    access-key-id: LTAI5tKANx9e16FZyD5GTvGJ
    access-key-secret: avlQ0ULiCPQy3EHlukUmXIaVwpNeoz
    bucket-name: web-tlias-hjl0519
